" Para números de línea relativos
set number relativenumber
set nu rnu

" Para indentar con 4 espacios, y no con tab
set expandtab
set shiftwidth=2
set softtabstop=2

" Autoindent
set autoindent

" Para búsqueda de archivos
set wildmenu
set hidden

" Para highlightear las búsquedas, y que sea case insensitive a menos que haya
" una mayúscula
set ignorecase
set smartcase
set hlsearch

" Para que las ventanas nuevas se abran a la derecha y abajo
set splitbelow
set splitright

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

" Map to run current file as python script
cmap rpy !python % 

" Plugins
" plug.vim install
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" plugins
call plug#begin('~/.vim/plugged')

Plug 'ekalinin/dockerfile.vim'

call plug#end()
