" leader
let mapleader = ' '

" Para números de línea relativos
set number relativenumber
set nu rnu

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()
function! TrimWhiteSpace()
    %s/\s\+$//e
endfunction

" Para indentar con 4 espacios, y no con tab
set expandtab
set shiftwidth=4
set softtabstop=4

" Autoindent
set autoindent
" set smartindent

" Para búsqueda de archivos
set wildmenu
set hidden

" Para cambiar de directorio automáticamente
"set autochdir

" Para highlightear las búsquedas, y que sea case insensitive a menos que haya
" una mayúscula
set ignorecase
set smartcase
set hlsearch

" Para que las ventanas nuevas se abran a la derecha y abajo
set splitbelow
set splitright

" Enable viewing man page in vim by ":Man ..."
runtime ftplugin/man.vim

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

" self explanatory
set pastetoggle=<F3>

" swap, backup and undo dirs
set backup                  " Backups are nice ...
set undofile                " So is persistent undo ...

if isdirectory($HOME . '/.vim/.swap') == 0
   :silent !mkdir -p ~/.vim/.swap >/dev/null 2>&1
endif
set directory=~/.vim/.swap//

if isdirectory($HOME . '/.vim/.backup') == 0
   :silent !mkdir -p ~/.vim/.backup >/dev/null 2>&1
endif
set backupdir=~/.vim/.backup//

if isdirectory($HOME . '/.vim/.undo') == 0
   :silent !mkdir -p ~/.vim/.undo >/dev/null 2>&1
endif
set undodir=~/.vim/.undo//

au FileType javascript,typescript,typescriptreact setlocal sw=2 ts=2 sts=2 expandtab

" setlocal noswapfile

" prevent Rg from matching filenames
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>), 1, {'options': '--delimiter : --nth 4..'}, <bang>0)
command! -bang -nargs=* Rgf call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>), 1, {}, <bang>0)
" command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".string(<q-args>), 1, {'options': '--delimiter : --nth 4..'}, <bang>0)
" command! -bang -nargs=? -complete=dir Files call ZfSelectFile()
let g:fzf_commits_log_options = 'git log --graph --all --decorate --oneline --pretty="%C(auto)%h  %C(auto)%d (%C(Green)%cr%C(reset))%x09 %C(Cyan)%an: %C(reset)%s"'

" find files
nnoremap <silent> <Leader>f :Files<CR>
" nnoremap <silent> <Leader>f :call ZfSelectFile()<CR>
nnoremap <silent> <Leader>F :FZF -q <C-R><C-W><CR>
nnoremap <silent> <Leader>b :Buffers<CR>
" map Rg
nnoremap <silent> <Leader>g :Rg<CR>

" Rg selected word
:nnoremap <expr> <silent> <Leader>w ':Rg '.expand('<cword>').'<CR>'
:nnoremap <expr> <silent> -w ':Rgf '.expand('<cword>').'<CR>'

nnoremap <leader>l :BLines<CR>

" archivos .conf.template con sintaxis nginx
autocmd BufNewFile,BufRead *.conf.template set syntax=nginx

" Automatically call AnsiEsc command and TrimWhiteSpace() function
"augroup LogFiles
  "autocmd!
  " Call AnsiEsc command and TrimWhiteSpace() function only if it hasn't been called before in the current buffer
  "autocmd BufReadPost,BufWritePost *.log if !exists("b:ansiEscCalled") | AnsiEsc | let b:ansiEscCalled = 1 | endif
  "autocmd BufReadPost,BufWritePost *.log call TrimWhiteSpace()
"augroup END

" Plugins
" plug.vim install
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" plugins
call plug#begin('~/.vim/plugged')

    Plug 'tpope/vim-fugitive'
    "Plug 'bling/vim-airline'
    Plug 'itchyny/lightline.vim'
    Plug 'vhda/verilog_systemverilog.vim'

    " fzf installed with git
    Plug '/home/mperezandrade/.fzf'
    Plug 'junegunn/fzf.vim'

    " local vimrc
    Plug 'embear/vim-localvimrc'

    " escape sequences
    " Plug 'vim-scripts/AnsiEsc.vim'
    " Plug 'powerman/vim-plugin-AnsiEsc'

    " todo syntax
    Plug 'freitass/todo.txt-vim'

    " search visual text
    Plug 'bronson/vim-visual-star-search'

    " SKILL syntax
    "Plug 'augustunderground/vim-skill'

    " lf
    "Plug 'ptzz/lf.vim'
    "Plug 'voldikss/vim-floaterm'

    " replace netrw
    Plug 'justinmk/vim-dirvish'
    " Plug 'tpope/vim-vinegar'

    " replace buggy YAML syntax
    Plug 'stephpy/vim-yaml'

    " alignment
    Plug 'junegunn/vim-easy-align'
    " this one aligns to tab
    " Plug 'jeffreydwalter/vim-easy-align'

    " zf
    Plug 'ratfactor/zf.vim'

    " GV, commit browser
    " requires fugitive
    Plug 'junegunn/gv.vim'

    " peekabo, see registers and macros
    " slowed when large copy into buffer
    " Plug 'junegunn/vim-peekaboo'

    " vim slash, better search?
    " removes higlight etc, no fuzzy
    " Plug 'junegunn/vim-slash'

    " UltiSnips for snippets
    Plug 'sirver/ultisnips'

    " LaTeX snippets for Vim using UltiSnips (downloads only tagged releases)
    Plug 'ckunte/latex-snippets-vim', { 'tag': '*' }

    Plug 'pangloss/vim-javascript'
    Plug 'maxmellon/vim-jsx-pretty'

    Plug 'Konfekt/vim-DetectSpellLang'

    " Undo tree
    Plug 'mbbill/undotree'

    Plug 'prabirshrestha/vim-lsp'
    Plug 'mattn/vim-lsp-settings'
    Plug 'prabirshrestha/asyncomplete.vim'
    Plug 'prabirshrestha/asyncomplete-lsp.vim'

    Plug 'github/copilot.vim'

call plug#end()

let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<c-j>'
let g:UltiSnipsJumpBackwardTrigger = '<c-k>'

autocmd FileType verilog_systemverilog setlocal nosmartindent
autocmd FileType verilog_systemverilog setlocal autoindent

"autocmd BufNewFile,BufRead *TODO* set filetype=markdown
autocmd BufNewFile,BufRead *.ill set filetype=skill

autocmd BufRead,BufNewFile *.rdl set filetype=systemrdl

autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | silent! pclose | endif

" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

let g:easy_align_delimiters = {
\ '(': { 'pattern': '(' },
\ ')': { 'pattern': ')' },
\ }

" to assign E to explore (since easyalign provides ambiguity)
" from https://stackoverflow.com/a/14367507/7139191
command! -nargs=* -bar -bang -count=0 -complete=dir E Explore <args>

" lightline config
set laststatus=2
set noshowmode

"let g:localvimrc_whitelist = '/home/mperezandrade/projects/980151/.lvimrc'
"let g:localvimrc_whitelist = ['/native/mperezandrade/projects/980151/.lvimrc', '/native/mperezandrade/projects/dac/.lvimrc']
let g:localvimrc_whitelist = [
  \ '/home/mperezandrade/projects/\(980151\|980161\|178021\|sdm\|dsp_pkg\)/.*',
  \ '/home/miguel/dev/asic/compiler/.*'
  \ ]

function! MyTabLine()
    let s = ''
    let wn = ''
    let t = tabpagenr()
    let i = 1
    while i <= tabpagenr('$')
        let buflist = tabpagebuflist(i)
        let winnr = tabpagewinnr(i)
        let s .= '%' . i . 'T'
        let s .= (i == t ? '%1*' : '%2*')
        let s .= ' '
        let wn = tabpagewinnr(i,'$')

        let s .= '%#TabNum#'
        let s .= i
        " let s .= '%*'
        let s .= (i == t ? '%#TabLineSel#' : '%#TabLine#')
        let bufnr = buflist[winnr - 1]
        let file = bufname(bufnr)
        let buftype = getbufvar(bufnr, 'buftype')
        if buftype == 'nofile'
            if file =~ '\/.'
                let file = substitute(file, '.*\/\ze.', '', '')
            endif
        else
            let file = fnamemodify(file, ':p:t')
        endif
        if file == ''
            let file = '[No Name]'
        endif
        let s .= ' ' . file . ' '
        let i = i + 1
    endwhile
    let s .= '%T%#TabLineFill#%='
    let s .= (tabpagenr('$') > 1 ? '%999XX' : 'X')
    return s
endfunction
set tabline=%!MyTabLine()
highlight link TabNum Special
set tabpagemax=15
hi TabLineSel term=bold cterm=bold ctermfg=16 ctermbg=229
hi TabWinNumSel term=bold cterm=bold ctermfg=90 ctermbg=229
hi TabNumSel term=bold cterm=bold ctermfg=16 ctermbg=229

hi TabLine term=underline ctermfg=16 ctermbg=145
hi TabWinNum term=bold cterm=bold ctermfg=90 ctermbg=145
hi TabNum term=bold cterm=bold ctermfg=16 ctermbg=145

" to avoid unreadable dark blue
set background=dark

autocmd FileType tex setlocal spell
set spelllang=en,es
" Use aspell
let g:detectspelllang_program = 'aspell'

" Languages to test (order doesn't matter)
let g:detectspelllang_langs = ['en', 'es']

" How many lines around cursor to analyze
let g:detectspelllang_lines = 40

" Nice netrw
" let g:netrw_banner=0
" let g:netrw_liststyle=3
" let g:netrw_fastbrowse=1
" let g:netrw_keepdir = 0

let g:loaded_netrwPlugin = 1
command! -nargs=? -complete=dir Explore Dirvish % <args>
command! -nargs=? -complete=dir Sexplore belowright split | silent Dirvish % <args>
command! -nargs=? -complete=dir Vexplore rightbelow vsplit | silent Dirvish % <args>
au FileType dirvish nmap - <plug>(dirvish_up)

" Don't highlight word on cursor
let g:lsp_document_highlight_enabled = 0

" --- vim-lsp diagnostics: show only on current line ---

" Enable diagnostics
" let g:lsp_diagnostics_enabled = 1

" Show floating message ONLY when cursor is on the line
" let g:lsp_diagnostics_float_cursor = 1
" let g:lsp_diagnostics_float_delay = 0

" Disable inline virtual text
" let g:lsp_diagnostics_virtual_text_enabled = 0

" Keep gutter signs + underline highlights
" let g:lsp_diagnostics_signs_enabled = 1
" let g:lsp_diagnostics_highlights_enabled = 1

" Open LSP location in tab, reusing existing tab if buffer is already open
function! LspGotoTab(cmd) abort
    let l:orig_tab = tabpagenr()
    let l:orig_buf = bufnr('%')
    let l:orig_view = winsaveview()

    execute 'tab Lsp' . a:cmd

    let l:cur_tab = tabpagenr()
    let l:target_buf = bufnr('%')
    let l:target_line = line('.')
    let l:target_col = col('.')

    " If still in same tab (LSP found nothing or same file)
    if l:cur_tab == l:orig_tab
        return
    endif

    " Restore original tab's buffer if it was changed
    execute 'tabnext ' . l:orig_tab
    if bufnr('%') != l:orig_buf
        silent execute 'buffer ' . l:orig_buf
        call winrestview(l:orig_view)
    endif

    " Check if target buffer exists in another tab (besides the new one)
    let l:existing_tab = -1
    let l:existing_win = -1
    for l:tabnr in range(1, tabpagenr('$'))
        if l:tabnr == l:cur_tab
            continue
        endif
        let l:buflist = tabpagebuflist(l:tabnr)
        let l:idx = index(l:buflist, l:target_buf)
        if l:idx != -1
            let l:existing_tab = l:tabnr
            let l:existing_win = l:idx + 1
            break
        endif
    endfor

    if l:existing_tab != -1
        " Close the new tab and go to existing one
        execute 'tabclose ' . l:cur_tab
        if l:existing_tab > l:cur_tab
            let l:existing_tab -= 1
        endif
        execute 'tabnext ' . l:existing_tab
        execute l:existing_win . 'wincmd w'
        call cursor(l:target_line, l:target_col)
    else
        " Go back to the new tab
        execute 'tabnext ' . l:cur_tab
    endif
endfunction

for [key, cmd] in items({
\ 'd': 'Definition',
\ 'D': 'Declaration',
\ 'i': 'Implementation',
\ 'r': 'References',
\ 'y': 'TypeDefinition',
\ })
  execute 'nnoremap g'.key.' :Lsp'.cmd.'<CR>'
  execute 'nnoremap Vg'.key.' :vertical Lsp'.cmd.'<CR>'
  execute 'nnoremap Hg'.key.' :belowright Lsp'.cmd.'<CR>'
  execute 'nnoremap Tg'.key.' :call LspGotoTab("'.cmd.'")<CR>'
endfor
nnoremap <silent> <Leader>r :LspRename<CR>

nmap [g <plug>(lsp-previous-diagnostic)
nmap ]g <plug>(lsp-next-diagnostic)
nnoremap <leader>dq :LspDiagnostics<CR>:copen<CR>

" Copy: break <file>:<line> to system clipboard (filename only)
nnoremap <leader>d :let @+ = 'break ' . expand('%:t') . ':' . line('.')<CR>

function! LspDiagnosticsOff()
    let b:lsp_diagnostics_enabled = 0
    edit
    echo "LSP diagnostics OFF (buffer)"
endfunction

function! LspDiagnosticsOn()
    let b:lsp_diagnostics_enabled = 1
    edit
    echo "LSP diagnostics ON (buffer)"
endfunction

nnoremap <leader>tdo :call LspDiagnosticsOff()<CR>
nnoremap <leader>tdi :call LspDiagnosticsOn()<CR>

function! LspDiagStatus() abort
    let l:enabled = get(b:, 'lsp_diagnostics_enabled',
          \ get(g:, 'lsp_diagnostics_enabled', 1))
    return l:enabled ? 'LSP:ON' : 'LSP:OFF'
endfunction

let g:lightline = {
\ 'active': {
\   'right': [ [ 'lineinfo' ],
\              [ 'percent' ],
\              [ 'lspdiag', 'fileformat', 'fileencoding', 'filetype' ] ]
\ },
\ 'component_function': {
\   'lspdiag': 'LspDiagStatus'
\ }
\ }
  let g:lsp_settings = {
  \  'pylsp-all': {
  \    'workspace_config': {
  \      'pylsp': {
  \        'plugins': {
  \          'pycodestyle': {
  \            'ignore': ['E501', 'E241'],
  \          },
  \          'flake8': {
  \            'ignore': ['E501'],
  \          },
  \        },
  \      },
  \    },
  \  },
  \}
