" Para números de línea relativos
set number relativenumber
set nu rnu

" Para indentar con 4 espacios, y no con tab
set expandtab
set shiftwidth=2
set softtabstop=2

" Autoindent
set autoindent
set smartindent

" Para búsqueda de archivos
set wildmenu
set hidden

" Para cambiar de directorio automáticamente
set autochdir
let g:netrw_keepdir=0

" Para highlightear las búsquedas, y que sea case insensitive a menos que haya
" una mayúscula
set ignorecase
set smartcase
set hlsearch

" Para que las ventanas nuevas se abran a la derecha y abajo
set splitbelow
set splitright

" Enable viewing man page in vim by ":Man ..."
runtime ftplugin/man.vim

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

" Map to run current file as python script
cmap rpy !python % 
map <F2> <Esc>:w<CR>:!python %<CR>

" self explanatory
set pastetoggle=<F3>

" Para no ver archivos swp en netrw
let g:netrw_list_hide= '.*\.swp$'

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" colors
" set termguicolors
if exists('+termguicolors')
  let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif

" archivos .conf.template con sintaxis nginx
autocmd BufNewFile,BufRead *.conf.template set syntax=nginx

let g:ale_completion_enabled = 0

" Plugins
" plug.vim install
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" plugins
call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-fugitive'
Plug 'bling/vim-airline'

Plug 'ekalinin/dockerfile.vim'
Plug 'chr4/nginx.vim'
Plug 'evidens/vim-twig'

Plug 'lervag/vimtex'
Plug 'ludovicchabant/vim-gutentags'
Plug 'sirver/ultisnips'
Plug 'honza/vim-snippets'

Plug 'eslint/eslint'
"Plug 'dense-analysis/ale'
"Plug 'autozimu/LanguageClient-neovim', {
    "\ 'branch': 'next',
    "\ 'do': 'bash install.sh',
    "\ }
"if has('nvim')
  "Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
"else
  "Plug 'Shougo/deoplete.nvim'
  "Plug 'roxma/nvim-yarp'
  "Plug 'roxma/vim-hug-neovim-rpc'
"endif
Plug 'natebosch/vim-lsc'
"Plug 'neoclide/coc.nvim'

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

Plug 'bluz71/vim-nightfly-guicolors'
Plug 'ParamagicDev/vim-medic_chalk'

call plug#end()

autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | silent! pclose | endif

nnoremap <C-p> :GFiles<Cr>

let g:tex_flavor = 'latex'
let g:vimtex_view_general_viewer = 'zathura'

let g:deoplete#enable_at_startup = 1

" colorscheme nightfly
colorscheme medic_chalk

let g:lsc_server_commands = {
 \  'javascript': {
 \    'command': 'typescript-language-server --stdio',
 \    'log_level': -1,
 \    'suppress_stderr': v:true,
 \  }
 \}

let g:LanguageClient_serverCommands = {
    \ 'javascript': ['typescript-language-server --stdio'],
    \ }
let g:ale_linters = {
\   'javascript': ['eslint'],
\}
" Complete default mappings are:
let g:lsc_auto_map = {
    \ 'GoToDefinition': '<C-}>',
    \ 'GoToDefinitionSplit': ['<C-W>]', '<C-W><C-}>'],
    \ 'FindReferences': 'gr',
    \ 'NextReference': '<C-n>',
    \ 'PreviousReference': '<C-p>',
    \ 'FindImplementations': 'gI',
    \ 'FindCodeActions': 'ga',
    \ 'Rename': 'gR',
    \ 'ShowHover': v:true,
    \ 'DocumentSymbol': 'go',
    \ 'WorkspaceSymbol': 'gS',
    \ 'SignatureHelp': 'gm',
    \ 'Completion': 'completefunc',
    \}
