" Para números de línea relativos
set number relativenumber
set nu rnu

" Para indentar con 4 espacios, y no con tab
set expandtab
set shiftwidth=2
set softtabstop=2

" Autoindent
set autoindent
set smartindent

" Para búsqueda de archivos
set wildmenu
set hidden

" Para cambiar de directorio automáticamente
set autochdir

" Para highlightear las búsquedas, y que sea case insensitive a menos que haya
" una mayúscula
set ignorecase
set smartcase
set hlsearch

" Para que las ventanas nuevas se abran a la derecha y abajo
set splitbelow
set splitright

" Enable viewing man page in vim by ":Man ..."
runtime ftplugin/man.vim

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

" Map to run current file as python script
cmap rpy !python % 
map <F2> <Esc>:w<CR>:!python %<CR>

" Para no ver archivos swp en netrw
let g:netrw_list_hide= '.*\.swp$'

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" archivos .conf.template con sintaxis nginx
autocmd BufNewFile,BufRead *.conf.template set syntax=nginx

" Plugins
" plug.vim install
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" plugins
call plug#begin('~/.vim/plugged')

Plug 'ekalinin/dockerfile.vim'
Plug 'tpope/vim-fugitive'
Plug 'bling/vim-airline'
Plug 'chr4/nginx.vim'
Plug 'evidens/vim-twig'
Plug 'lervag/vimtex'
Plug 'sirver/ultisnips'

" Use release branch (Recommend)
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

let g:deoplete#enable_at_startup = 1
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | silent! pclose | endif

let g:tex_flavor = 'latex'
let g:vimtex_view_general_viewer = 'zathura'


